### ISSUE TITLE
[PoC] Elemental IP Address Management

### ISSUE THREAD

**Issue by fgiudici** [rancher/elemental#1459]
Elemental does not address network configuration of booted machines.
Provided Elemental OS images demand network configuration to the installed network management tool, NetworkManager, which by default provide a DHCP connection on the available ethernet interface.

Custom Network configuration can be achieved through the creation of networking configuration files through could-config files (see the [Networking section](https://elemental.docs.rancher.com/networking) of the [Elemental docs](https://elemental.docs.rancher.com))

If a DHCP server is not available on the network, static IP address configuration requires creating individual NetworkManager network profiles for each host, which is impractical.

To overcome this limitation the Elemental Operator should be extended with an [IPAM](https://en.wikipedia.org/wiki/IP_address_management) solution, able to provide a centralized IP address management without DHCP.

The envisioned solution involves the following steps:
- The host boots from a generated SeedImage boot image and gets a temporary IP address to complete the registration.
- The Elemental Operator requests an IP address from the IPAM provider at the host registration time and sends the retrieved IP address to the registering machine together the other installation data.
- The host performs the Elemental OS installation configuring the assigned IP address statically.
- Elemental Machines provisioning and lifecycle is performed as usual.

Identified sub-tasks:
- [x] https://github.com/rancher/elemental/issues/1460
- [x] https://github.com/rancher/elemental-operator/issues/756
- [x] https://github.com/rancher/elemental/issues/1461

**Comment by anmazzotti** [comment]
The PoC is successful, so we can close this epic.
