### ISSUE TITLE
Enable SELinux

### ISSUE THREAD

**Issue by kkaempf** [rancher/elemental#251]
SL Micro comes with SELinux fully supported.

The Elemental stack should leverage this and also provide SELinux support.

There might be packages missing, like
- selinux-rancher
- selinux-k3s
- ... ?

Identified basic subtasks:
- [x] rancher/elemental-toolkit#2054
- [x] rancher/elemental-toolkit#1492
- [x] https://github.com/rancher/elemental/issues/1359
- [x] https://github.com/rancher/elemental/issues/1361
- [ ] https://github.com/rancher/elemental/issues/1362
- [x] https://github.com/rancher/elemental/issues/1360
- [x] https://github.com/rancher/elemental/issues/1372
- [x]  https://github.com/rancher/elemental/issues/1403

**Comment by kkaempf** [comment]
SELinux training video: https://youtu.be/91pxilczl2I

**Comment by kkaempf** [comment]
How it's done for RKE2: https://github.com/rancher-sandbox/cluster-api-provider-rke2/issues/198

**Comment by fgiudici** [comment]
related issue with dev image: https://github.com/rancher/elemental-operator/issues/699

**Comment by fgiudici** [comment]
Identified basic subtasks:
- [ ] rancher/elemental-toolkit#1492
- [ ] https://github.com/rancher/elemental/issues/1359
- [ ] https://github.com/rancher/elemental/issues/1360
- [ ] https://github.com/rancher/elemental/issues/1372
- [ ] https://github.com/rancher/elemental/issues/1361
- [ ] https://github.com/rancher/elemental/issues/1362
