### ISSUE TITLE
Acceptance tests

### ISSUE THREAD

**Issue by mudler** [rancher/elemental#28]
Currently our smoke tests are testing the following aspects (the vbox ones are more complete, due to accelleration support in the runners):

- CD datasource and first-user configuration
- First services on boot starts correctly (ros-operator, rancherd, k3s, etc)
- Starting up a k3s cluster on rancherd and installing the ros-operator on top (rancherd included)
- Creation of MachineRegistration resources

In order to have an acceptance test suite, we should at least cover the following aspects:

- Node upgrades managed by `ros-operator`
- Manual node upgrades from the CLI
- Installation and bootstrap of nodes from ISO and #6 
- Multi-machine tests

## Action items

Enhance our test suite on github actions with new test scenarios:
- [x] Bootstrapping nodes with MachineRegistration. Currently our test suite generates MachineRegistration resources but are not consumed. Consider tests for both ISO and container images (depends on #6) (split in https://github.com/rancher-sandbox/os2/issues/41)
- [x] Node upgrades following https://rancher.github.io/os2/upgrade/#rancheros (split in https://github.com/rancher-sandbox/os2/issues/42)
- [x] Manual upgrades, following cOS default usage and `ros-installer` (split in https://github.com/rancher-sandbox/os2/issues/43) - In progress
- [x] Upgrades in a multi-node environment. After machines are bootstrapped, the test suite should try to upgrade the nodes with the `ManagedOs` resource and also manually from the cli (split in https://github.com/rancher-sandbox/os2/issues/44)
- [ ] Use ISO and container image to boot some VMs in the E2E tests (https://github.com/rancher/elemental/issues/147)

**Comment by kkaempf** [comment]
considered done
