### ISSUE TITLE
Feature Checklist - Definition of Done from Rancher QA

### ISSUE THREAD

**Issue by ldevulder** [rancher/elemental#288]
This is a place holder to discussion on feature checklist from Rancher QA. We need to specify what will be implemented from this checklist and what is not applicable.

https://confluence.suse.com/pages/viewpage.action?spaceKey=EN&title=Feature+Checklist+-+Definition+of+Done

- [x] RBAC
- [ ] Upgrade
- [ ] Cluster type and architecture
- [ ] Rollback/Downgrade
- [ ] Rancher Backup
- [ ] Airgap
- [ ] Rancher Proxy
- [ ] Downstream Cluster Proxy
- [ ] Private CA Certificate/Self Signed Certs
- [ ] Network Isolation
- [ ] SELinux
- [ ] Hardened Cluster
- [ ] Secure Credentials
- [ ] Certificates/Keys Rotation/Replacement
- [ ] Rancher CLI
- [ ] Terraform
- [ ] Windows
- [ ] Feature Parity (Acceptance Criteria)
- [ ] Licensing

Anything that gets implemented from this checklist, Elemental QA will add it to its test plan and test it.

**Comment by kkaempf** [comment]
This is what @agracey and I think is important:

* [ ] Users & authentication roles
  * Andrew to create respective issues
* [ ]  Upgrade
  * upgrade of elemental-operator
  * upgrade of Elemental Teal
* [ ]  Cluster type and architecture
  * RKE2 & k3s, x86_64 only
* [ ]  Airgap
* [ ]  Private CA Certificate/Self Signed Certs
* [ ]  SELinux
  * details tbd
* [ ]  Hardened Cluster
* [ ]  Rancher CLI

>     * [ ]  Rancher Proxy - need to find out
>     * [ ]  Downstream Cluster Proxy - need to find out

**Comment by agracey** [comment]
I'm pretty sure the "hardened cluster" means that a CIS benchmark runs. Due to the immutable nature of the OS, there's not much corrective action that can be taken by the admin. We should make sure that the CIS benchmark passes ourselves.

**Comment by agracey** [comment]
Also, for Airgap: There may be some complexity only because of the typical Rancher airgap tooling. The plugin model may break the standard process and require additional documentation.

**Comment by agracey** [comment]
I'm interested in if the rancher cli will pick up the new API automatically or if there are changes needed? I would assume it reflects the API similar to how the UI does.

**Comment by prabalsharma** [comment]
Rancher QA test plan discussion: https://confluence.suse.com/display/RANQA/Elemental?focusedCommentId=1084162072#comment-1084162072

**Comment by ldevulder** [comment]
What is the Rancher CLI and how to use it/test it?

**Comment by ldevulder** [comment]
@agracey @kkaempf Could we agree on a list of what needs to be tested for the release? As the deadline is pretty close :-)

**Comment by agracey** [comment]
Here are the basic tests that I think are important when it comes to the extension:

* [ ]  Users & authentication roles
  * An admin user see and manage the Elemental objects without any additional set up
  * An non admin user should not see the elemental objects until the correct rolebinding is added
* [ ]  Upgrade
  * The elemental-operator should be able to be upgraded without needing manual migrations 
  * An upgrade of the base OS (Elemental Teal) should be able to be performed from the UI
* [ ]   Cluster type and architecture
  * An admin should be able to provision both RKE2 and K3s clusters (x86 only for now)
* [ ]   Private CA Certificate/Self Signed Certs
  * An admin should be able to use any type of certificate that is supported by Rancher
* [ ] Backup / Restore
  * A backup of the Rancher cluster should include the CRs for Elemental. 
  * A restore should put them back in the right place without requiring any change to devices in the machine inventory 


These should work as is so we just need smoke tests:
* [ ]   Hardened Cluster
  * The CIS benchmark can be run on clusters made up of nodes running Elemental Teal
* [ ]   Rancher CLI
  * An admin can manage the elemental-operator CRDs via rancherctl
* [ ]  Downstream Cluster Proxy
  * A cluster running on Elemental Teal can be accessed via the proxy


In my opinion, airgap is out of scope for this release. 

Lastly, I'm unsure about SE Linux's status in the stack. If this is ready, we should make sure that it is enabled and works as expected (cluster is deployed and workloads can be scheduled)

**Comment by kkaempf** [comment]
Considered done
