### ISSUE TITLE
UI - Test Elemental UI with Cypress

### ISSUE THREAD

**Issue by juadk** [rancher/elemental#292]
This epic ticket summarizes all the steps we have to do to get a complete test suite.
The full test plan is [here](https://confluence.suse.com/display/CECO/UI+testing+plan).

## Cypress tests:

- [x] Machine registration (https://github.com/rancher/elemental/issues/196, https://github.com/rancher/elemental/issues/222)
- [x] Machine inventory (https://github.com/rancher/elemental/issues/295)
- [x] Machine Inventory Selectors (https://github.com/rancher/elemental/issues/314)
- [x] Machine Inventory Selectors Templates (https://github.com/rancher/elemental/issues/314)
- [x] Managed OS Versions (https://github.com/rancher/elemental/issues/357)
- [x] Managed OS Version Channels (https://github.com/rancher/elemental/issues/357)
- [ ] Delete OS Version Channels and OS Versions (https://github.com/rancher/elemental/issues/500)
- [x] OS Image Upgrades (https://github.com/rancher/elemental/issues/335)
- [x] Test RBAC role (https://github.com/rancher/elemental/issues/385)

## Infra automation:
- [x] Add the first tests in the CI https://github.com/rancher/elemental/issues/199
- [x] Adapt the CI to use 2 machines for testing cluster integration (like machine inventory) https://github.com/rancher/elemental/pull/296
- [x] Move the CI to GCP (https://github.com/rancher/elemental/issues/338)

## CI:
You can see first tests running [here](https://github.com/rancher/elemental/actions/workflows/ui-e2e.yaml)

**Comment by juadk** [comment]
### Status:

1. UI tests are running in the CI [here](https://github.com/rancher/elemental/actions/workflows/ui-e2e.yaml).
2. Other tests cannot be done yet due to this bug https://github.com/rancher/dashboard/issues/6710, we cannot download the registration file anymore (error 500).
@prabalsharma told us that the UI tests are not high priority anymore.

**Comment by juadk** [comment]
> we should get back to this, once we are unblocked.

I think I can found a workaround waiting the fix, downloading the registration file with a curl command, I will try.

**Comment by juadk** [comment]
Status badges have been added to the main README:
![image](https://user-images.githubusercontent.com/6025636/187370819-703e21aa-1efa-4d71-b15e-e914a8e0b7dc.png)

**Comment by juadk** [comment]
Machine inventory and cluster creation are done with default options. To achieve this test, a new automation was added to deploy a VM inside the worker.
Basically, Rancher is running on the worker and the test configures a VM with libvirt used as an Elemental node.

**Comment by juadk** [comment]
Just added cases regarding RBAC and moving tests to GCP.
I also have to debug why tests are flaky since last week.

**Comment by juadk** [comment]
Now we got the new Elemental plugin, I have to validate all the existing tests with.
https://github.com/rancher/elemental/issues/445

**Comment by juadk** [comment]
RBAC tests have been added in https://github.com/rancher/elemental/pull/491 as well as code adaptation to match elemental-ui plugin v0.1.1
I think I can close this card and continue small things in separate issues like the cloud config test.
