### ISSUE TITLE
Refactor and clean up Grub2 setup

### ISSUE THREAD

**Issue by davidcassany** [rancher/elemental#323]
This is an issue (probably epic) that encompasses few Grub2 related changes. The main reason I tried to put them together is because bootloader changes are sensitive and we should avoid regular changes in that area. So probably we can encompass those all together.

- [x] #151 (done, however we keep the issue opened until SLE includes loopback and squashfs modules for the grub2 EFI signed images)
- [ ] rancher/elemental-cli#297 (nice to have, no strict requirement for the RC)
- [ ] #324 (currently affecting only BIOS firmware installs, so not that relevant, however still a low hanging fruit)
- [ ] #325 (nice to have, but not for now, no changes on the boot procedure before RC)

**Comment by kkaempf** [comment]
Closing this issue as the main part is done. The remaining issues stay open but are not in scope right now.
