### ISSUE TITLE
CRD and controller for OS versions

### ISSUE THREAD

**Issue by mudler** [rancher/elemental#58]
In order to be able to select available versions to upgrade our nodes into from UI or either `kubectl`, we need a generic `ManagedOSVersion` CRD/controller and a `ManagedOSVersionChannel` CRD to represent the version we want to upgrade into, and how we get all the lists of available versions. This will also help us later on with moving image validation steps inside the kubernetes cluster with a kubewarden policy (as we can validate releases both while fetching new ones, and while applying them)

- [x] #67 
- [x] https://github.com/rancher-sandbox/os2/issues/59
- [x] https://github.com/rancher-sandbox/rancheros-operator/pull/7
- [x] https://github.com/rancher-sandbox/os2/issues/78
- [x] https://github.com/rancher-sandbox/os2/issues/64
- [x] https://github.com/rancher-sandbox/os2/issues/63
- [x] https://github.com/rancher-sandbox/os2/issues/84
- [ ] https://github.com/rancher-sandbox/os2/issues/85
- [x] https://github.com/rancher-sandbox/os2/issues/86
- [x] https://github.com/rancher-sandbox/os2/issues/87
- [x] https://github.com/rancher-sandbox/rancheros-operator/issues/16
- [x] https://github.com/rancher-sandbox/rancheros-operator/issues/17
- [x] https://github.com/rancher-sandbox/rancheros-operator/issues/18
- [ ] https://github.com/rancher-sandbox/cOS-toolkit/issues/1183

## Notes

API defintions: https://github.com/rancher-sandbox/os2/blob/master/pkg/apis/rancheros.cattle.io/v1/os.go#L28

**Comment by mudler** [comment]
Closing this as we have the mechanism in place. we have already follow-ups for the low-hanging fruit work
