### ISSUE TITLE
e2e: Use RKE2 as a management node

### ISSUE THREAD

**Issue by juadk** [rancher/elemental#648]
Until now, we are only using k3s to host Rancher manager.
But if we want to test hardened RKE2 cluster, we will have to also use RKE2 as management node.

- [x] Configure RKE2 as management node for UI upgrade tests ( RKE2) / https://github.com/rancher/elemental/issues/830
- [x] Configure RKE2  as management node for other UI tests (RKE2) / https://github.com/rancher/elemental/pull/835
- [x] Configure RKE2  as management node for CLI tests (RKE2) / https://github.com/rancher/elemental/pull/844

Edit: 
This issue has been converted to an epic due to the amount of tasks to achieve.
The main reason is PXE/DHCP traffic is blocked by RKE2/Calico and I did not success to add my rules. Anyway, PXE boot is tested in the K3S tests.

**Comment by agracey** [comment]
Annoyingly, we have use cases for both RKE2 and K3s as the distro for the management cluster. (just as a heads up)

**Comment by ldevulder** [comment]
For the first version of the test we will have to remove the backup/restore test of Elemental, as by default there is no local storage with RKE2. At least we should keep this in mind during the automation.

**Comment by juadk** [comment]
I don't know why yet but when RKE2 is used as upstream cluster, PXE boot does not work anymore...
https://github.com/rancher/elemental/actions/runs/4874297797/jobs/8695062379

**Comment by juadk** [comment]
After checking with Loic, the culprit seems to be the firewall rules brought by RKE2.

**Comment by juadk** [comment]
All is done! RKE2 is now used as upstream cluster (instead of K3s) when the workflow provision RKE2 as downstream cluster, like that we keep some logical:
```
Downstream K3s => use K3s upstream to host RM
Downstream RKE2 => use RKE2 upstream to host RM
```
