### ISSUE TITLE
e2e UI: Test upgrade in a dedicated test

### ISSUE THREAD

**Issue by juadk** [rancher/elemental#659]
Follow up of https://github.com/rancher/elemental/issues/651

Until now, we test all the thing in one test and that's not the proper way to test upgrade.
For testing upgrade, we have to install from stable and then upgrade to dev/staging.

We will probably use this https://github.com/rancher/elemental/issues/649

That means we need to switch upgrade from our nightly test and move it to a second nightly test.

- [x] Disable upgrade in our main scenario https://github.com/rancher/elemental/pull/679
- [x] Research a way to tell Cypress which tests to run https://github.com/rancher/elemental/issues/680
- Add the new upgrade tests:
- [ ] Upgrade with osImage https://github.com/rancher/elemental/pull/683
- [ ] Upgrade by using OS Channels (not ready yet in the UI)

**Comment by juadk** [comment]
Upgrade test was disabled in our main scenario https://github.com/rancher/elemental/pull/679.
Let's write another test to handle upgrade.

**Comment by juadk** [comment]
We will probably use this https://github.com/rancher/elemental/issues/649
