### ISSUE TITLE
[epic] Airgap deployments

### ISSUE THREAD

**Issue by davidcassany** [rancher/elemental#894]
An epic as it can be seen from three different angles:

- [ ] From customers PoV (set an airgap rancher runtime including elemental images, explore airgapped provisioning)
- [ ] From QA PoV (testing IBS builds before release, aka use a given registry inside a VPN)
- [ ] From Developers PoV (testing pure local builds in a local env)

----
Sub-issues:
- [x] https://github.com/rancher/elemental/issues/937
- [x] https://github.com/rancher/elemental-operator/issues/496
- [x] https://github.com/rancher/elemental-operator/issues/503
- [x] https://github.com/rancher/elemental/issues/950
- [x] https://github.com/rancher/elemental-operator/issues/547
- [x] https://github.com/rancher/elemental-ui/issues/135
- [x] https://github.com/rancher/elemental-docs/issues/219
- [x] https://github.com/rancher/elemental-operator/issues/528

**Comment by fgiudici** [comment]
Looked at how airgap is managed in Rancher Marketplace, guess we can do (almost) the same.
Sharing here for evaluation.

### how airgap is managed in Rancher Marketplace
the container images are defined with a _image.repository_ value that just points to the container image _path_, like:
`repository: rancher/backup-restore-operator` ([sample reference](https://github.com/rancher/charts/blob/dev-v2.7/charts/rancher-backup/102.0.1%2Bup3.1.1/values.yaml#L2))
the value.yaml file also contains:
`global.cattle.systemDefaultRegistry: ""` ([sample reference](https://github.com/rancher/charts/blob/dev-v2.7/charts/rancher-backup/102.0.1%2Bup3.1.1/values.yaml#L50-L52))
The _systemDefaultRegistry_ contains the private registry to support the airgap story in Rancher.

Using Helm templating, it is then rendered properly. So, the reference in the templated resources will be something like:
`image: {{ template "system_default_registry" . }}{{ .Values.image.repository }}:{{ .Values.image.tag }}` ([sample reference](https://github.com/rancher/charts/blob/dev-v2.7/charts/rancher-backup/102.0.1%2Bup3.1.1/templates/deployment.yaml#L33))

The template is defined [here](https://github.com/rancher/charts/blob/dev-v2.7/charts/rancher-backup/102.0.1%2Bup3.1.1/templates/_helpers.tpl#L1-L7).

### we can do (almost) the same
We can do something similar, moving the  `image.repository` value in our chart from:
`"registry.opensuse.org/isv/rancher/elemental/stable/teal53/15.4/rancher/elemental-operator/5.3"`
to:
`"rancher/elemental-operator/5.3"`
then using in the resource template the same as rancher:
`image: {{ template "system_default_registry" . }}{{ .Values.image.repository }}:{{ .Values.image.tag }}`

but of course, we will define our template. Thinking to something like:
```
{{- define "system_default_registry" -}}
{{- if .Values.global.cattle.systemDefaultRegistry -}}
{{- printf "%s/" .Values.global.cattle.systemDefaultRegistry -}}
{{- else -}}
{{- "registry.opensuse.org/isv/rancher/elemental/stable/teal53/15.4/" -}}
{{- end -}}
{{- end -}}
```

**Comment by fgiudici** [comment]
Sub-issues:
- [ ] Airgap PoC https://github.com/rancher/elemental/issues/937
- [ ] ...
